---
title: "OMSBA 5300 Data Translation Project"
author: "Elizabeth, John, Julius, Raymond, Schyuler"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(jtools)
library(vtable)
library(car)
library(estimatr)
library(lubridate)
library(readr)
library(ggplot2)
library(ggpubr)
library(fastDummies)
```

## Import Data

```{r}
# Set default working directory
setwd('/Users/cray/Desktop/OMSBA5300/OMSBA5300_DTP/Data')

if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("cps_00006.xml")
data <- read_ipums_micro(ddi)

StateCode <- read_csv('State_FIPS.csv')

StateCode <- StateCode %>% 
  select(State, STATEFIP)

Industries <- read_csv('indnames.csv')

Occupations <- read_csv('Occupation.csv')

Industries <- Industries %>%
  mutate(Industry = indname, IND = ind) %>%
  select(-indname, -ind) %>% 
  filter(Industry %in% c('Manufacturing', 
                         'Retail Trade', 
                         'Information',
                         'Arts, Entertainment, and Recreation, and Accommodation and Food Services')) %>% 
  mutate(Industry = case_when(Industry == 'Retail Trade' ~ 'Retail',
                              Industry == 'Manufacturing' ~ 'Manufacturing',
                              Industry == 'Information' ~ 'Information',
                              Industry == 'Arts, Entertainment, and Recreation, and Accommodation and Food Services' ~ 'Arts, Leisure and Hospitality'))
  

# vtable(data)

```


## Data Cleaning

```{r}
class_converted <- data %>%
  mutate(ASECFlag = as_factor(lbl_clean(ASECFLAG)),
         FoodStampRecipient = as_factor(lbl_clean(FOODSTMP)),
         Sex = as_factor(lbl_clean(SEX)),
         LaborForce = as_factor(lbl_clean(LABFORCE)),
         COVIDTelework = as_factor(lbl_clean(COVIDTELEW)),###### has NIU
         COVIDUnableToWork = as_factor(lbl_clean(COVIDUNAW)),###### has NIU
         COVIDUnableToLookForWork = as_factor(lbl_clean(COVIDLOOK)),###### has NIU
         FamilyIncome = as_factor(lbl_clean(FAMINC))
         ) %>% 
  select(-c(ASECFLAG, FOODSTMP, SEX, COVIDTELEW, COVIDUNAW, COVIDLOOK, FAMINC, LABFORCE))

df <- class_converted %>% 
  select(-SERIAL) %>% 
  mutate(AgeGroup = case_when(AGE < 20 ~ 'under20',
                               AGE >= 20 & AGE < 30 ~ '20to29',
                               AGE >= 30 & AGE < 40 ~ '30to39',
                               AGE >= 40 & AGE < 50 ~ '40to49',
                               AGE >= 50 & AGE < 60 ~ '50to59',
                               AGE >= 60 ~ 'over60')) %>% 
  mutate(Regions = case_when(REGION == 11 | REGION == 12 ~ 'Northeast',
                             REGION == 21 | REGION == 22 ~ 'Midwest',
                             REGION == 31 | REGION == 32 | REGION == 33 ~ 'South',
                             REGION == 41 | REGION == 42 ~ 'West',
                             REGION == 97 ~ 'Unknown')) %>% 
  select(-REGION) %>% 
  mutate(MetroArea = case_when(METRO %in% c(0, 4, 9) ~ 'Others',
                               METRO == 1 ~ 'Rural',
                               METRO == 2 ~ 'Urban',
                               METRO == 3 ~ 'Suburb')) %>% 
  select(-METRO) %>% 
  mutate(Race = case_when(HISPAN == 0 & RACE == 100 ~ 'White',
                          HISPAN == 0 & RACE == 200 ~ 'Black',
                          HISPAN == 0 & RACE %in% c(650, 651, 652) ~ 'Asian',
                          HISPAN == 0 & !(RACE %in% c(100, 200, 650, 651, 652)) ~ 'Others',
                          HISPAN != 0 ~ 'Latino')) %>% 
  select(-ASIAN, -HISPAN, -RACE) %>%
  mutate(Married = ifelse(MARST == 1, 1, 0)) %>% 
  select(-MARST) %>% 
  left_join(StateCode, by = 'STATEFIP') %>% 
  select(-STATEFIP) %>% 
  inner_join(Industries, by = 'IND') %>% 
  select(-IND) %>% 
  mutate(Education = case_when(EDUC >= 10 & EDUC <= 72 ~ 'NoHighschool',
                               EDUC == 73 ~ 'HighschoolNoCollege',
                               EDUC %in% c(80, 81, 90, 100, 110, 120, 121, 122, 91, 92) ~ 'SomeCollegeAssociateDegree',
                               EDUC == 111 ~ 'BachelorDegree',
                               EDUC %in% c(123,124,125) ~ 'GraduateDegreeOrHigher',
                               EDUC %in% c(0, 1, 2, 999) ~ 'NA')) %>%  
  select(-EDUC) %>% 
  filter(Education != 'NA') %>% 
  mutate(Employed = case_when(EMPSTAT <= 1 | EMPSTAT >= 30 ~ 'Others', 
                               EMPSTAT >= 10 &  EMPSTAT < 20 ~ '1',
                               EMPSTAT >= 20 &  EMPSTAT < 30 ~ '0'
                               )) %>% 
  select(-EMPSTAT) %>%
  mutate(WorkStatus = case_when(WKSTAT %in% c(10,11,14,15) ~ 'Full Time',
                                 WKSTAT %in% c(12,20,21,22,40,41) ~ 'Part Time',
                                 WKSTAT %in% c(13,42,50,60) ~ 'Unemployed',
                                 WKSTAT == 99 ~ 'NA' )) %>% 
  select(-WKSTAT) %>% 
  mutate(UnemploymentReason = ifelse(WHYUNEMP==1, 'Layoff', 'Other')) %>% 
  select(-WHYUNEMP) %>% 
  mutate(PartTimeReason = case_when(!(WHYPTLWK %in% c(52, 60, 101, 121, 122)) ~ 'Others',
                                    WHYPTLWK == 52 ~ 'Job Terminated',
                                    WHYPTLWK == 60 ~ 'Could Only Find PT',
                                    WHYPTLWK == 101 ~ 'Health Limitation',
                                    WHYPTLWK == 121 ~ 'Childcare Problem',
                                    WHYPTLWK == 122 ~ 'Other Personal Obligations')) %>% 
  select(-WHYPTLWK, -OCC) %>% 
  filter(Employed != 'Others') %>% 
  filter(!is.na(WTFINL)) #check with Schyuler

df$Employed <- as.numeric(df$Employed)
  
vtable(df)

```


## Data Exploration

```{r}
df_2019 <- df %>% 
  filter(YEAR == 2019)

df_2020 <- df %>% 
  filter(YEAR == 2020)

## Unemployment Rate by Industries
unemp_ind_2020 <- df_2020 %>% 
  group_by(Industry, MONTH) %>% 
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL)) %>% 
  mutate(Diff = AvgUnempRate - lag(AvgUnempRate))

ggplot(data = unemp_ind_2020, aes(x = MONTH, y = AvgUnempRate, color = Industry, shape = Industry)) +
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE) +
  xlim('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12') +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Month') +
  theme_bw()

unemp_retail_month <- df %>% 
  filter(Industry == 'Retail') %>% 
  group_by(MONTH, YEAR) %>% 
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL)) %>% 
  mutate(Diff = AvgUnempRate - lag(AvgUnempRate))

unemp_retail_month$YEAR <- as.factor(unemp_retail_month$YEAR)

ggplot(data = unemp_retail_month, aes(x = MONTH, y = AvgUnempRate, color = YEAR)) +
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE) +
  xlim('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12') +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Month') +
  theme_bw()

## Industry - Income
IndInc_2020 <- df_2020 %>%
  group_by(Industry, FamilyIncome) %>%
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL))

ggplot(data = IndInc_2020, aes(x = FamilyIncome, y = AvgUnempRate, fill = Industry)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Family Income Level') +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0))

RetailInc <- df_2020 %>% 
  filter(Industry == 'Retail') %>% 
  group_by(FamilyIncome) %>% 
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL))

ggplot(data = RetailInc, aes(x = FamilyIncome, y = AvgUnempRate)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Family Income Level') +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0))


## Industry - Race
RaceInd_2020 <- df_2020 %>%
  group_by(Industry, Race) %>%
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL))

ggplot(data = RaceInd_2020, aes(x = Race, y = AvgUnempRate, fill = Industry)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Race') +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0))


## Industry - Age
AgeInd_2020 <- df_2020 %>%
  group_by(Industry, AgeGroup) %>%
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL))

ggplot(data = AgeInd_2020, aes(x = AgeGroup, y = AvgUnempRate, fill = Industry)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Age Group') +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0))


## Industry - Sex
SexInd_2020 <- df_2020 %>%
  group_by(Industry, Sex) %>%
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL))

ggplot(data = SexInd_2020, aes(x = Sex, y = AvgUnempRate, fill = Industry)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Sex') +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0))

## Industry - Education
EduInd_2020 <- df_2020 %>%
  group_by(Industry, Education) %>%
  summarize(AvgUnempRate = 1 - weighted.mean(Employed, w = WTFINL))

ggplot(data = EduInd_2020, aes(x = Education, y = AvgUnempRate, fill = Industry)) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  ylab('Average Unemployment Rate') +
  xlab('Education Level') +
  theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0))

m19 <- glm(Employed ~ Industry, data = df_2019, family = binomial('probit'), weights = WTFINL)
m20 <- glm(Employed ~ Industry, data = df_2020, family = binomial('probit'), weights = WTFINL)

export_summs(m19, m20)

```

